version: '3.8'
services:
    php-apache:
        container_name: webphp-apache
        build:
            context: ./php
            dockerfile: Dockerfile-php
        depends_on:
            - mysqldb
        volumes:
            - ./php/:/var/www/html/
        user: nobody
        ports:
            - 8000:80

    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"

    reactjs-app:
        container_name: rjs
        build:
            context: .
            dockerfile: Dockerfile-ReactJS
        depends_on:
            - php-apache
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

